# Generated by Django 3.2.6 on 2021-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamNow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_media_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movies'), ('tv', 'Tv Show')], default='h', max_length=60),
        ),
    ]
