# Generated by Django 3.2.6 on 2021-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamNow', '0002_auto_20210910_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('movie', 'movie'), ('tv', 'tv')], default='h', max_length=60),
        ),
    ]
